server:
  port: 8081
  servlet:
    context-path: /code-evaluation

spring:
  application:
    name: code-evaluation-service
  
  # Logging configuration
logging:
  level:
    com.university.codeevaluation: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Swagger/OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Code evaluation configuration
code-evaluation:
  timeout:
    seconds: 10
  max-memory:
    mb: 512
  temp-dir: ${java.io.tmpdir}/code-evaluation
